[Distribution]
Distribution=fedora
Release=44
Architecture=x86-64

[Output]
Format=disk
Output=lga-fedora
ImageId=lga-fedora
ImageVersion=1
ManifestFormat=json

[Content]
Packages=
        dbus-broker
        kernel
        mokutil
        openssh-server
        podman
        sudo
        systemd-networkd
        systemd-ukify
        tpm2-tools
        util-linux
WithDocs=no
Bootable=yes
Bootloader=uki
UnifiedKernelImages=auto
KernelCommandLine=console=ttyS0 network-config=disabled rd.systemd.show_status=auto ro systemd.log_level=info

[Validation]
SecureBoot=yes
SecureBootAutoEnroll=no
Verity=yes
